trigger:
- main

variables:
  versionprefix: 0.2.0

jobs:
  - job: 'BuildPackage'
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-18.04'
          rid: 'linux-x64'

    pool:
      vmImage: $(imageName)

    variables:
      buildConfiguration: 'Release'

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        includePreviewVersions: true
        version: 7.0.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    - task: CmdLine@2
      displayName: 'Install linux dependencies'
      condition: eq(variables.rid, 'linux-x64')
      inputs:
        script: 'sudo apt-get update && sudo apt-get install build-essential cmake ninja-build python python3 zlib1g-dev'
    - task: CmdLine@2
      displayName: 'Build .NET runtime for WASI'
      inputs:
        script: |
          cd modules/runtime/src/mono/wasi
          make
    - task: CmdLine@2
      displayName: 'Build .NET libraries'
      inputs:
        script: |
          cd modules/runtime/src/mono/wasm
          make provision-wasm
          make build-all
    - task: CmdLine@2
      displayName: 'dotnet pack WASI SDK'
      inputs:
        script: |
          dotnet pack -c $(buildConfiguration) dotnet-wasi-sdk.sln /p:VersionPrefix=$(versionprefix) /p:VersionSuffix=$(Build.BuildNumber)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'artifacts'
        ArtifactName: 'artifacts'
        publishLocation: 'Container'
