name: BuildAll

on:
  push:
    branches: [ main, ci-build ]
  pull_request:
    branches: [ main ]

env:
  PACKAGE_VERSION_PREFIX: 0.2.0
  DOTNET_BUILD_CONFIG: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install build-essential cmake ninja-build python python3 zlib1g-dev
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true

    - run: echo "RUNTIME_SUBMODULE_COMMIT=$(git rev-parse HEAD:modules/runtime)" >> $GITHUB_ENV
    - name: Cache .NET libraries build output
      uses: actions/cache@v2
      id: cache-dotnet-libraries-build
      with:
        path: ./modules/runtime/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm
        key: ${{ runner.OS }}-cache-dotnet-libraries-build-${{ env.RUNTIME_SUBMODULE_COMMIT }}
    - name: Build .NET libraries
      run: cd modules/runtime/src/mono/wasm && make provision-wasm && make build-all
      if: steps.cache-dotnet-libraries-build.outputs.cache-hit != 'true'

    - name: Build .NET runtime for WASI
      run: cd modules/runtime/src/mono/wasi && make
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack dotnet-wasi-sdk.sln /c ${{ env.DOTNET_BUILD_CONFIG }} /p:VersionPrefix=${{ env.PACKAGE_VERSION_PREFIX }} /p:VersionSuffix=${{ github.run_number }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts/*
