name: BuildAll

on:
  push:
    branches: [ main, ci-build ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install build-essential cmake ninja-build python python3 zlib1g-dev
    - uses: actions/checkout@v3
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    - name: Build .NET runtime for WASI
      run: cd modules/runtime/src/mono/wasi && make
    - name: Build .NET libraries
      run: cd modules/runtime/src/mono/wasm && make provision-wasm && make build-all
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      run: dotnet pack
